spring.application.name=demo

spring.profiles.active=dev
spring.jpa.open-in-view=true

spring.main.allow-circular-references=true

# Documentation
springdoc.swagger-ui.path =/docs-park.html
springdoc.api-docs.path =/docs-park
springdoc.packagesToScan=com.example.demo.web.controller
